# 네트워크
bind 192.168.0.5
port 6379
protected-mode yes

# 데이터 저장 경로
dir /data

# RDB
save 300 1
dbfilename dump.rdb

# AOF
appendonly yes
appendfsync everysec

# 메모리
maxmemory 3gb
maxmemory-policy allkeys-lru

# ACL
aclfile /usr/local/etc/redis/users.acl

# 로그
loglevel notice
logfile ""